imagePullPolicy: Always

#
# Settings for API nodes
#
apiNode:
  image: barrywalker/bjr
  imageTag: latest
  nodeSelector: {}
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 512Mi
      cpu: 500m
  replicas: 2

#
# Settings for worker nodes
#
workerNode:
  image: barrywalker/bjr
  imageTag: latest
  nodeSelector: {}
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 512Mi
      cpu: 500m
  replicas: 2

#
# Settings for BJR web nodes
#
webNode:
  image: barrywalker/bjr_web
  imageTag: latest
  nodeSelector: {}
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 128Mi
      cpu: 100m
  replicas: 2

#
# BJR Settings
#
serverSettings:
  jwtLifetime: 3600


#
# MySQL settings
#
mysql:
  useKubernetesMySQL: false
  mysqlDatabase: bjr_production
  mysqlUser: bjr
  timezone: UTC
  imageTag: '8.0'
  persistence:
    enabled: true
    size: 8Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 200m
    limits:
      memory: 256Mi
      cpu: 200m
  livenessProbe:
    initialDelaySeconds: 120
  readinessProbe:
    initialDelaySeconds: 120
  external:
    secretName: bjr-external-mysql
    usernameKey: mysql-username
    passwordKey: mysql-password
    address: "192.168.1.209"
    database: "bjr_production"
  configurationFiles:
    mysql.cnf: |-
      [mysqld]
      init_connect='SET collation_connection = utf8mb4_unicode_ci; SET NAMES utf8mb4'
      innodb_strict_mode=1
      character-set-server=utf8mb4
      collation-server=utf8mb4_unicode_ci
      default-authentication-plugin=mysql_native_password

      [client]
      default-character-set=utf8mb4

#
# Redis settings
#
redis:
  useKubernetesRedis: true
  usePassword: false
  external:
    address: ""
    port: 6379
    sidekiqDb: 0
  cluster:
    enabled: false
