#
# BJR Server image and tag
#
image: "barrywalker71/bjr"
imageTag: "latest"
imagePullPolicy: Always

apiNode:
  nodeSelector: {}
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 512Mi
      cpu: 500m
  replicas: 2

workerNode:
  nodeSelector: {}
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 512Mi
      cpu: 500m
  replicas: 2

#
# BJR Settings
#
serverSettings:
  jwtLifetime: 3600


#
# MySQL settings
#
mysql:
  mysqlDatabase: bjr_production
  mysqlUser: bjr
  timezone: UTC
  persistence:
    enabled: true
    size: 8Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 200m
    limits:
      memory: 256Mi
      cpu: 200m
  livenessProbe:
    initialDelaySeconds: 120
  readinessProbe:
    initialDelaySeconds: 120
  external:
    disabled: true
    secretName: bjr-mysql
    usernameKey: mysql-username
    passwordKey: mysql-password
    address: ""
    database: ""

#
# Redis settings
#
redis:
  usePassword: false
  external:
    disabled: true
    address: ""
    port: 6379
    sidekiqDb: 0
  cluster:
    enabled: false
