imagePullPolicy: Always

#
# Settings for API nodes
#
apiNode:
  image: barrywalker71/bjr
  imageTag: latest
  nodeSelector: {}
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 512Mi
      cpu: 500m
  replicas: 2

#
# Settings for worker nodes
#
workerNode:
  image: barrywalker71/bjr
  imageTag: latest
  nodeSelector: {}
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 512Mi
      cpu: 500m
  replicas: 2

#
# Settings for BJR web nodes
#
webNode:
  image: barrywalker71/bjr_web
  imageTag: latest
  nodeSelector: {}
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 128Mi
      cpu: 100m
  replicas: 2

#
# BJR Settings
#
serverSettings:
  jwtLifetime: 3600


#
# MySQL settings
#
mysql:
  mysqlDatabase: bjr_production
  mysqlUser: bjr
  timezone: UTC
  persistence:
    enabled: true
    size: 8Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 200m
    limits:
      memory: 256Mi
      cpu: 200m
  livenessProbe:
    initialDelaySeconds: 120
  readinessProbe:
    initialDelaySeconds: 120
  external:
    disabled: true
    secretName: bjr-mysql
    usernameKey: mysql-username
    passwordKey: mysql-password
    address: ""
    database: ""

#
# Redis settings
#
redis:
  usePassword: false
  external:
    disabled: true
    address: ""
    port: 6379
    sidekiqDb: 0
  cluster:
    enabled: false
