/* 
 * BJR API V1
 *
 * API specification for the BJR job server.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BJR.Api;
using BJR.Model;
using BJR.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BJR.Test
{
    /// <summary>
    ///  Class for testing BusyThreadCountMessageObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BusyThreadCountMessageObjectTests
    {
        // TODO uncomment below to declare an instance variable for BusyThreadCountMessageObject
        //private BusyThreadCountMessageObject instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BusyThreadCountMessageObject
            //instance = new BusyThreadCountMessageObject();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BusyThreadCountMessageObject
        /// </summary>
        [Test]
        public void BusyThreadCountMessageObjectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" BusyThreadCountMessageObject
            //Assert.IsInstanceOf(typeof(BusyThreadCountMessageObject), instance);
        }


        /// <summary>
        /// Test the property 'TotalBusy'
        /// </summary>
        [Test]
        public void TotalBusyTest()
        {
            // TODO unit test for the property 'TotalBusy'
        }
        /// <summary>
        /// Test the property 'Hosts'
        /// </summary>
        [Test]
        public void HostsTest()
        {
            // TODO unit test for the property 'Hosts'
        }

    }

}
