/* 
 * BJR API V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BJR.Api;
using BJR.Model;
using BJR.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BJR.Test
{
    /// <summary>
    ///  Class for testing SingleUserMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SingleUserMessageTests
    {
        // TODO uncomment below to declare an instance variable for SingleUserMessage
        //private SingleUserMessage instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SingleUserMessage
            //instance = new SingleUserMessage();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SingleUserMessage
        /// </summary>
        [Test]
        public void SingleUserMessageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SingleUserMessage
            //Assert.IsInstanceOfType<SingleUserMessage> (instance, "variable 'instance' is a SingleUserMessage");
        }


        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'IsError'
        /// </summary>
        [Test]
        public void IsErrorTest()
        {
            // TODO unit test for the property 'IsError'
        }
        /// <summary>
        /// Test the property 'ObjectType'
        /// </summary>
        [Test]
        public void ObjectTypeTest()
        {
            // TODO unit test for the property 'ObjectType'
        }
        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Test]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }
        /// <summary>
        /// Test the property 'Object'
        /// </summary>
        [Test]
        public void ObjectTest()
        {
            // TODO unit test for the property 'Object'
        }

    }

}
