/* 
 * BJR API V1
 *
 * API specification for the BJR job server.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BJR.Api;
using BJR.Model;
using BJR.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BJR.Test
{
    /// <summary>
    ///  Class for testing TodaysStats
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TodaysStatsTests
    {
        // TODO uncomment below to declare an instance variable for TodaysStats
        //private TodaysStats instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TodaysStats
            //instance = new TodaysStats();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TodaysStats
        /// </summary>
        [Test]
        public void TodaysStatsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TodaysStats
            //Assert.IsInstanceOf(typeof(TodaysStats), instance);
        }


        /// <summary>
        /// Test the property 'TotalJobs'
        /// </summary>
        [Test]
        public void TotalJobsTest()
        {
            // TODO unit test for the property 'TotalJobs'
        }
        /// <summary>
        /// Test the property 'TotalJobsTrend'
        /// </summary>
        [Test]
        public void TotalJobsTrendTest()
        {
            // TODO unit test for the property 'TotalJobsTrend'
        }
        /// <summary>
        /// Test the property 'EnabledJobs'
        /// </summary>
        [Test]
        public void EnabledJobsTest()
        {
            // TODO unit test for the property 'EnabledJobs'
        }
        /// <summary>
        /// Test the property 'EnabledJobsTrend'
        /// </summary>
        [Test]
        public void EnabledJobsTrendTest()
        {
            // TODO unit test for the property 'EnabledJobsTrend'
        }
        /// <summary>
        /// Test the property 'RunJobs'
        /// </summary>
        [Test]
        public void RunJobsTest()
        {
            // TODO unit test for the property 'RunJobs'
        }
        /// <summary>
        /// Test the property 'RunJobsTrend'
        /// </summary>
        [Test]
        public void RunJobsTrendTest()
        {
            // TODO unit test for the property 'RunJobsTrend'
        }
        /// <summary>
        /// Test the property 'FailedJobs'
        /// </summary>
        [Test]
        public void FailedJobsTest()
        {
            // TODO unit test for the property 'FailedJobs'
        }
        /// <summary>
        /// Test the property 'FailedJobsTrend'
        /// </summary>
        [Test]
        public void FailedJobsTrendTest()
        {
            // TODO unit test for the property 'FailedJobsTrend'
        }
        /// <summary>
        /// Test the property 'AvgJobRuntime'
        /// </summary>
        [Test]
        public void AvgJobRuntimeTest()
        {
            // TODO unit test for the property 'AvgJobRuntime'
        }
        /// <summary>
        /// Test the property 'AvgJobRuntimeTrend'
        /// </summary>
        [Test]
        public void AvgJobRuntimeTrendTest()
        {
            // TODO unit test for the property 'AvgJobRuntimeTrend'
        }
        /// <summary>
        /// Test the property 'MaxJobRuntime'
        /// </summary>
        [Test]
        public void MaxJobRuntimeTest()
        {
            // TODO unit test for the property 'MaxJobRuntime'
        }
        /// <summary>
        /// Test the property 'MaxJobRuntimeTrend'
        /// </summary>
        [Test]
        public void MaxJobRuntimeTrendTest()
        {
            // TODO unit test for the property 'MaxJobRuntimeTrend'
        }
        /// <summary>
        /// Test the property 'MinJobRuntime'
        /// </summary>
        [Test]
        public void MinJobRuntimeTest()
        {
            // TODO unit test for the property 'MinJobRuntime'
        }
        /// <summary>
        /// Test the property 'MinJobRuntimeTrend'
        /// </summary>
        [Test]
        public void MinJobRuntimeTrendTest()
        {
            // TODO unit test for the property 'MinJobRuntimeTrend'
        }
        /// <summary>
        /// Test the property 'AvgJobLag'
        /// </summary>
        [Test]
        public void AvgJobLagTest()
        {
            // TODO unit test for the property 'AvgJobLag'
        }
        /// <summary>
        /// Test the property 'AvgJobLagTrend'
        /// </summary>
        [Test]
        public void AvgJobLagTrendTest()
        {
            // TODO unit test for the property 'AvgJobLagTrend'
        }
        /// <summary>
        /// Test the property 'MaxJobLag'
        /// </summary>
        [Test]
        public void MaxJobLagTest()
        {
            // TODO unit test for the property 'MaxJobLag'
        }
        /// <summary>
        /// Test the property 'MaxJobLagTrend'
        /// </summary>
        [Test]
        public void MaxJobLagTrendTest()
        {
            // TODO unit test for the property 'MaxJobLagTrend'
        }
        /// <summary>
        /// Test the property 'MinJobLag'
        /// </summary>
        [Test]
        public void MinJobLagTest()
        {
            // TODO unit test for the property 'MinJobLag'
        }
        /// <summary>
        /// Test the property 'MinJobLagTrend'
        /// </summary>
        [Test]
        public void MinJobLagTrendTest()
        {
            // TODO unit test for the property 'MinJobLagTrend'
        }

    }

}
