/* 
 * BJR API V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BJR.Api;
using BJR.Model;
using BJR.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BJR.Test
{
    /// <summary>
    ///  Class for testing UserArray
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserArrayTests
    {
        // TODO uncomment below to declare an instance variable for UserArray
        //private UserArray instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserArray
            //instance = new UserArray();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserArray
        /// </summary>
        [Test]
        public void UserArrayInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserArray
            //Assert.IsInstanceOfType<UserArray> (instance, "variable 'instance' is a UserArray");
        }



    }

}
