version: '3'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: bjr
      MYSQL_PASSWORD: bjr
    volumes:
      - mysql:/var/lib/mysql
  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      REDIS_HOST: redis
      BJR_DATABASE_HOST: db
  sidekiq:
    build: .
    command: bash -c "bundle exec sidekiq"
    environment:
      REDIS_HOST: redis
  redis:
    image: redis:latest

volumes:
  mysql:
