version: '3.7'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: bjr
      MYSQL_PASSWORD: bjr
      MYSQL_DATABASE: bjr_development
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - mysql:/var/lib/mysql
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      REDIS_HOST: redis
      BJR_DATABASE_HOST: db
      BJR_DATABASE_USERNAME: bjr
      BJR_DATABASE_PASSWORD: bjr
      SERVER_TYPE: api
      RAILS_ENV: development
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      REDIS_HOST: redis
      BJR_DATABASE_HOST: db
      BJR_DATABASE_USERNAME: bjr
      BJR_DATABASE_PASSWORD: bjr
      SERVER_TYPE: worker
      RAILS_ENV: development
  redis:
    image: redis:latest

volumes:
  mysql:
