version: '3.7'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    env_file:
    - .env.development
    volumes:
      - mysql:/var/lib/mysql
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
    - .env.development
    environment:
      SERVER_TYPE: api
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
    - .env.development
    environment:
      SERVER_TYPE: worker
  redis:
    image: redis:latest

volumes:
  mysql:
