version: '3'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: bjr
    volumes:
      - mysql:/var/lib/mysql
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      REDIS_HOST: redis
      BJR_DATABASE_HOST: db
      BJR_DATABASE_USERNAME: root
      BJR_DATABASE_PASSWORD: bjr
      SERVER_TYPE: api
      RAILS_ENV: development
  sidekiq:
    build: .
    environment:
      REDIS_HOST: redis
      BJR_DATABASE_HOST: db
      BJR_DATABASE_USERNAME: root
      BJR_DATABASE_PASSWORD: bjr
      SERVER_TYPE: worker
      RAILS_ENV: development
  redis:
    image: redis:latest

volumes:
  mysql:
