/**
 * BJR API V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from './ApiClient';
import AuthIn from './BJR.Model/AuthIn';
import AuthOut from './BJR.Model/AuthOut';
import JobIn from './BJR.Model/JobIn';
import JobOut from './BJR.Model/JobOut';
import JobOutObject from './BJR.Model/JobOutObject';
import UserNewIn from './BJR.Model/UserNewIn';
import UserOut from './BJR.Model/UserOut';
import UserOutObject from './BJR.Model/UserOutObject';
import UserUpdateIn from './BJR.Model/UserUpdateIn';
import DefaultApi from './BJR.Api/DefaultApi';

/**
* Object.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var BjrApiV1 = require('BJR/index'); // See note below*.
* var xxxSvc = new BjrApiV1.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new BjrApiV1.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['BJR/index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new BjrApiV1.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new BjrApiV1.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module BJR/index
* @version v1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:BJR/ApiClient}
     */
    ApiClient,

    /**
     * The AuthIn model constructor.
     * @property {module:BJR/BJR.Model/AuthIn}
     */
    AuthIn,

    /**
     * The AuthOut model constructor.
     * @property {module:BJR/BJR.Model/AuthOut}
     */
    AuthOut,

    /**
     * The JobIn model constructor.
     * @property {module:BJR/BJR.Model/JobIn}
     */
    JobIn,

    /**
     * The JobOut model constructor.
     * @property {module:BJR/BJR.Model/JobOut}
     */
    JobOut,

    /**
     * The JobOutObject model constructor.
     * @property {module:BJR/BJR.Model/JobOutObject}
     */
    JobOutObject,

    /**
     * The UserNewIn model constructor.
     * @property {module:BJR/BJR.Model/UserNewIn}
     */
    UserNewIn,

    /**
     * The UserOut model constructor.
     * @property {module:BJR/BJR.Model/UserOut}
     */
    UserOut,

    /**
     * The UserOutObject model constructor.
     * @property {module:BJR/BJR.Model/UserOutObject}
     */
    UserOutObject,

    /**
     * The UserUpdateIn model constructor.
     * @property {module:BJR/BJR.Model/UserUpdateIn}
     */
    UserUpdateIn,

    /**
    * The DefaultApi service constructor.
    * @property {module:BJR/BJR.Api/DefaultApi}
    */
    DefaultApi
};
