/**
 * BJR API V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The JobOut model module.
* @module BJR/BJR.Model/JobOut
* @version v1
*/
export default class JobOut {
    /**
    * Constructs a new <code>JobOut</code>.
    * @alias module:BJR/BJR.Model/JobOut
    * @class
    */

    constructor() {
        
        AnyOfoutModelObject.call(this);
        
    }

    /**
    * Constructs a <code>JobOut</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:BJR/BJR.Model/JobOut} obj Optional instance to populate.
    * @return {module:BJR/BJR.Model/JobOut} The populated <code>JobOut</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JobOut();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('cron')) {
                obj['cron'] = ApiClient.convertToType(data['cron'], 'String');
            }
            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('command')) {
                obj['command'] = ApiClient.convertToType(data['command'], 'String');
            }
            if (data.hasOwnProperty('next_run')) {
                obj['next_run'] = ApiClient.convertToType(data['next_run'], 'String');
            }
            if (data.hasOwnProperty('running')) {
                obj['running'] = ApiClient.convertToType(data['running'], 'Boolean');
            }
            if (data.hasOwnProperty('timezone')) {
                obj['timezone'] = ApiClient.convertToType(data['timezone'], 'String');
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
        }
        return obj;
    }

    /**
    * The unique id of the job.
    * @member {Number} id
    */
    id = undefined;
    /**
    * The name of the job.
    * @member {String} name
    */
    name = undefined;
    /**
    * The cron expression for the job.
    * @member {String} cron
    */
    cron = undefined;
    /**
    * Whether the job is enabled or not.
    * @member {Boolean} enabled
    */
    enabled = undefined;
    /**
    * The command that is executed when the job fires.
    * @member {String} command
    */
    command = undefined;
    /**
    * The date and time of the job's next run.
    * @member {String} next_run
    */
    next_run = undefined;
    /**
    * Whether the job is currently running.
    * @member {Boolean} running
    */
    running = undefined;
    /**
    * The timezone that the job will run in.
    * @member {String} timezone
    */
    timezone = undefined;
    /**
    * An array of tags associated with the job.
    * @member {Array.<String>} tags
    */
    tags = undefined;

    // Implement AnyOfoutModelObject interface:
    


}
