"""
    BJR API V1

    API specification for the BJR job server.  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import bjr4py
from bjr4py.api.authentication_api import AuthenticationApi  # noqa: E501


class TestAuthenticationApi(unittest.TestCase):
    """AuthenticationApi unit test stubs"""

    def setUp(self):
        self.api = AuthenticationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_authenticate_user(self):
        """Test case for authenticate_user

        Authenticates a user and returns a token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
