# coding: utf-8

"""
    BJR API V1

    API specification for the BJR job server.  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import bjr4py
from bjr4py.models.single_job_message import SingleJobMessage  # noqa: E501
from bjr4py.rest import ApiException

class TestSingleJobMessage(unittest.TestCase):
    """SingleJobMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SingleJobMessage
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = bjr4py.models.single_job_message.SingleJobMessage()  # noqa: E501
        if include_optional :
            return SingleJobMessage(
                message = '0', 
                is_error = True, 
                object_type = '0', 
                status_code = 56, 
                object = bjr4py.models.single_job.SingleJob(
                    id = 56, 
                    name = '0', 
                    cron = '0', 
                    enabled = True, 
                    command = '0', 
                    next_run = '0', 
                    running = True, 
                    timezone = '0', 
                    tags = [
                        '0'
                        ], 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    success_callback = '0', 
                    failure_callback = '0', )
            )
        else :
            return SingleJobMessage(
        )

    def testSingleJobMessage(self):
        """Test SingleJobMessage"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
