"""
    BJR API V1

    API specification for the BJR job server.  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bjr4py
from bjr4py.model.todays_stats import TodaysStats


class TestTodaysStats(unittest.TestCase):
    """TodaysStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTodaysStats(self):
        """Test TodaysStats"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TodaysStats()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
