/*
 * BJR API V1
 *
 * API specification for the BJR job server.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserNewIn {
    /// The new user's username. Must be unique.
    #[serde(rename = "username")]
    pub username: String,
    /// The new user's password.
    #[serde(rename = "password")]
    pub password: String,
    /// The new user's password confirmation. Must match 'password'.
    #[serde(rename = "password_confirmation")]
    pub password_confirmation: String,
}

impl UserNewIn {
    pub fn new(username: String, password: String, password_confirmation: String) -> UserNewIn {
        UserNewIn {
            username,
            password,
            password_confirmation,
        }
    }
}


