default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: 10
  username: <%= ENV.fetch('BJR_DATABASE_USERNAME', 'bjr') %>
  password: <%= ENV.fetch('BJR_DATABASE_PASSWORD', 'bjr') %>
  host: <%= ENV.fetch('BJR_DATABASE_HOST', '127.0.0.1') %>
  port: <%= ENV.fetch('BJR_DATABASE_PORT', 3306) %>
  database: <%= ENV.fetch('BJR_DATABASE', "bjr_#{Rails.env}") %>
  reaping_frequency: 0

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
