/*
 * BJR API V1
 *
 * API specification for the BJR job server.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BJR.Api;
using BJR.Model;
using BJR.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BJR.Test.Model
{
    /// <summary>
    ///  Class for testing UserUpdateIn
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserUpdateInTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserUpdateIn
        //private UserUpdateIn instance;

        public UserUpdateInTests()
        {
            // TODO uncomment below to create an instance of UserUpdateIn
            //instance = new UserUpdateIn();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserUpdateIn
        /// </summary>
        [Fact]
        public void UserUpdateInInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserUpdateIn
            //Assert.IsType<UserUpdateIn>(instance);
        }


        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'PasswordConfirmation'
        /// </summary>
        [Fact]
        public void PasswordConfirmationTest()
        {
            // TODO unit test for the property 'PasswordConfirmation'
        }

    }

}
