apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "bjr.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "bjr.fullname" . }}-web
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- with .Values.deploymentAnnotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.webNode.replicas }}
  selector:
    matchLabels:
      app: {{ template "bjr.fullname" . }}-web
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "bjr.fullname" . }}-web
        release: {{ .Release.Name }}
{{- with .Values.podLabels }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.webNode.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.webNode.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      containers:
      - name: {{ template "bjr.fullname" . }}-web
        image: "{{ .Values.webNode.image }}:{{ .Values.webNode.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        resources:
{{ toYaml .Values.apiNode.resources | indent 10 }}
        env:
        - name: RAILS_SERVE_STATIC_FILES
          value: "true"
        - name: RAILS_ENV
          value: production
        - name: RAILS_LOG_TO_STDOUT
          value: "true"
        - name: BJR_API_HOST
          value: http://bjr-api
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: {{ template "bjr.secretName" . }}
              key: secret-key-base
        {{- include "bjr.redis" . | nindent 8 }}
        - name: JWT_EXPIRY_SECONDS
          value: {{ .Values.serverSettings.jwtLifetime | quote }}
        ports:
        - name: web
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 120
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 120
          periodSeconds: 30
