apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "bjr.fullname" . }}-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: bjr-api.info
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "bjr.fullname" . }}-api
          servicePort: 3000
