apiVersion: v1
kind: Secret
metadata:
  name: {{ template "bjr.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "bjr.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  admin-password: {{ randAlphaNum 20 | b64enc | quote }}
  secret-key-base: {{ randAlphaNum 32 | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: bjr-external-mysql
  namespace:  {{ .Release.Namespace }}
type: Opaque
data:
  mysql-username: {{ "bjr" | b64enc | quote }}
  mysql-password: {{ "bjr" | b64enc | quote }}
