apiVersion: v1
kind: Secret
metadata:
  name: {{ template "bjr.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "bjr.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  admin-password: {{ randAlphaNum 20 | b64enc | quote }}
  secret-key-base: {{ randAlphaNum 32 | b64enc | quote }}
