apiVersion: v1
kind: Service
metadata:
  name: {{ template "bjr.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ template "bjr.fullname" . }}-api
    release: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "bjr.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ template "bjr.fullname" . }}-web
    release: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
