name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: bjr_test
          MYSQL_USER: bjr
          MYSQL_PASSWORD: bjr
          MYSQL_RANDOM_ROOT_PASSWORD: yes
        ports:
        - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - name: Execute RSpec tests
      env:
        RAILS_ENV: test
        BJR_DATABASE_PORT: ${{ job.services.mysql.ports[3306] }}
        BJR_DATABASE_HOST: 127.0.0.1
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        bundle exec rake
        bundle exec rake rswag

    - name: Build docker image
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
        docker build -t barrywalker71/bjr:latest .
        docker push barrywalker71/bjr:latest
