name: Ruby

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1

    - name: Execute RSpec tests
      env:
        BJR_DATABASE_PASSWORD: ${{ secrets.BJR_DATABASE_PASSWORD }}
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        RAILS_ENV=test bundle rake db:drop db:create db:migrate
        bundle exec rake

    - name: Build docker image
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
        docker build -t barrywalker71/bjr:latest .
        docker push barrywalker71/bjr:latest
